# Generated by Django 3.2.25 on 2024-04-01 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_auto_20240401_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='trip',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='destination',
            field=models.CharField(default='Default Destination', max_length=100),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='source',
            field=models.CharField(default='india', max_length=100),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='time',
            field=models.TimeField(default='12:00'),
        ),
    ]
