# Generated by Django 3.2.25 on 2024-04-01 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0003_auto_20240401_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='india', max_length=100)),
                ('destination', models.CharField(default='Default Destination', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default='12:00')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_received_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
