# Generated by Django 3.2.25 on 2024-04-06 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedrequest',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
