# Generated by Django 5.0.4 on 2024-04-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0008_acceptedrequest_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
