# Generated by Django 5.0.4 on 2024-04-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_customuser_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
